# Specify executable name
TARGET = timer_interrupt

# C source files
C_SOURCES = \
timerint.c \
$(VEGA_SDK_PATH)/drivers/hal_gpio.c \
$(VEGA_SDK_PATH)/drivers/hal_timer.c \
$(VEGA_SDK_PATH)/drivers/hal_interrupt.c 


include $(VEGA_SDK_PATH)/build.mk
