# Specify executable name
TARGET = vega

# C source files
C_SOURCES = \
uartprint.c \
syscalls.c \
sysmem.c \
$(VEGA_SDK_PATH)/drivers/hal_gpio.c \
$(VEGA_SDK_PATH)/drivers/hal_timer.c \
$(VEGA_SDK_PATH)/drivers/hal_interrupt.c \
$(VEGA_SDK_PATH)/drivers/hal_uart.c


include $(VEGA_SDK_PATH)/build.mk
