# Specify executable name
TARGET = timer_poll

# C source files
C_SOURCES = \
timerpoll.c \
$(VEGA_SDK_PATH)/drivers/hal_gpio.c \
$(VEGA_SDK_PATH)/drivers/hal_timer.c


include $(VEGA_SDK_PATH)/build.mk
