# Specify executable name
TARGET = vega_app

# C source files
# REMARK - To include all drivers: $(wildcard $(VEGA_SDK_PATH)/drivers/*.c)
C_SOURCES = \
main.c \
$(VEGA_SDK_PATH)/drivers/gpio.c

# C header include path(s)
C_INCLUDES = 

# Assembly (.s) source files
ASM_SOURCES = 

# AS Includes
AS_INCLUDES =

# Libraries
LIBS = 
LIBDIR =


include $(VEGA_SDK_PATH)/build.mk
